apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: nginx
        image: rosyriso/api-gateway-nginx
        ports:
        - containerPort: 80
      - name: frontend-service
        image: rosyriso/api-gateway-frontend-service
        ports:
        - containerPort: 5015

---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  selector:
    app: api-gateway
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5015
  type: LoadBalancer
