version: '3'
services:
  frontend-service:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5015:5015
    volumes:
      - .:/api-gateway
    image: meraviglioso8/gateway:latest
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      # - 443:443
    depends_on:
      - frontend-service
    image: meraviglioso8/gateway:latest