apiVersion: v1
kind: Secret
metadata:
  name: authenticationservice-secret
stringData:
  API_KEY: DlDyPrFIv0K2CgGu3xSjcUbzt5m5tCq6kG4yubgLacN0f4qnmojPXrRKMFrfjbSM
  DB_ENDPOINT: https://ap-southeast-1.aws.data.mongodb-api.com/app/data-wwzqj/endpoint/data/v1/action/
  SECRET_KEY: "-----BEGIN PRIVATE KEY-----\nMIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQg97mg6T3Nv0Q3aiRvfCk4X27rTLouHaw5VAGUfVLJZrmhRANCAATL1USAE9gSzKFdw/hHg1WLBgO8zuyda2tb5SVMmEQuwvSLBwm36arK3G3zX4FU6hS+EHrO+gdgriJUoBVEEso+\n-----END PRIVATE KEY-----"
type: Opaque
