apiVersion: v1
kind: Service
metadata:
  name: authenticationservice
spec:
  selector:
    app: authenticationservice
  type: ClusterIP
  ports:
    - port: 5012
      targetPort: 5012
      protocol: TCP