apiVersion: v1
kind: Service
metadata:
  name: authorizationservice
spec:
  selector:
    app: authorizationservice
  type: ClusterIP
  ports:
    - port: 7777
      targetPort: 7777
      protocol: TCP