apiVersion: v1
kind: Service
metadata:
  name: authorizationservice
spec:
  selector:
    app: authorizationservice
  type: ClusterIP
  ports:
    - port: 5013
      targetPort: 5013
      protocol: TCP