apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
  labels:
    app: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
      - name: authentication
        image: rosyriso/authentication
        ports:
        - containerPort: 5012
        env:
        - name: FLASK_ENV
          value: "production"

---
apiVersion: v1
kind: Service
metadata:
  name: authentication
  labels:
    app: authentication
spec:
  selector:
    app: authentication
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 5012
  type: LoadBalancer
