apiVersion: v1
kind: Service
metadata:
  name: productservice
spec:
  selector:
    app: productservice
  type: ClusterIP
  ports:
    - port: 8888
      targetPort: 8888
      protocol: TCP